repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: "23.7.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: '(^tests/expected_contents/.*\.txt$)|(^docs/(Components|Config)\.md$)'
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: '^docs/(Components|Config)\.md$'
