[build-system]
requires = ["pybind11", "pybind11_stubgen", "mypy"]
build-backend = "py_build_cmake.build"
backend-path = ["src"]

[project]
name = "py-build-cmake"
readme = "README.md"
requires-python = ">=3.8"
license = { "file" = "LICENSE" }
authors = [{ "name" = "Pieter P", "email" = "pieter.p@no-email.com" }]
keywords = ["pep517", "cmake"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
]
urls = { "Documentation" = "https://tttapa.github.io/" }
dependencies = ["distlib", "flit"]
dynamic = ["version", "description"]

# [tool.py-build-cmake.sdist]
# include = []
# exclude = ["test"]

[tool.py-build-cmake.cmake]
build_type = "Release"
# config = "Release"
# generator = "Ninja Multi-Config"
source_path = "."
# build_path = ".build"
options = { "WITH_PY_STUBS:BOOL" = "On" }
args = []
build_args = ["-j"]
build_tool_args = []
install_args = []
install_components = ["python_modules"]
# install_extra_components = ["python_modules"]
# env = { "SOME_VAR" = "$HOME/somefile" }

# [project.scripts]
# test_script = "py_build_cmake.test_script:main"

[tool.py-build-cmake.stubgen]
# packages = ["py_build_cmake"]
# modules = ["add_module"]
# files = []
args = ["-v"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["test"]
